"""update loan renewal structure

Revision ID: 5aea05f41e4a
Revises: cfd3cf3575ae
Create Date: 2026-07-22 19:15:55.766494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aea05f41e4a'
down_revision: Union[str, Sequence[str], None] = 'cfd3cf3575ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_renewals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_loan_id', sa.Integer(), nullable=False),
    sa.Column('new_loan_id', sa.Integer(), nullable=True),
    sa.Column('finance_owner_id', sa.Integer(), nullable=False),
    sa.Column('renewal_type', sa.String(length=20), nullable=False),
    sa.Column('old_due_date', sa.Date(), nullable=False),
    sa.Column('new_due_date', sa.Date(), nullable=False),
    sa.Column('old_interest_method', sa.String(length=20), nullable=False),
    sa.Column('new_interest_method', sa.String(length=20), nullable=False),
    sa.Column('old_interest_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_interest_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outstanding_interest', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('renewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finance_owner_id'], ['finance_owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_loan_id'], ['loans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_renewals_finance_owner_id'), 'loan_renewals', ['finance_owner_id'], unique=False)
    op.create_index(op.f('ix_loan_renewals_id'), 'loan_renewals', ['id'], unique=False)
    op.create_index(op.f('ix_loan_renewals_new_loan_id'), 'loan_renewals', ['new_loan_id'], unique=False)
    op.create_index(op.f('ix_loan_renewals_old_loan_id'), 'loan_renewals', ['old_loan_id'], unique=False)
    op.drop_constraint(op.f('finance_settings_finance_owner_id_key'), 'finance_settings', type_='unique')
    op.add_column('loans', sa.Column('parent_loan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loans', 'loans', ['parent_loan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_column('loans', 'parent_loan_id')
    op.create_unique_constraint(op.f('finance_settings_finance_owner_id_key'), 'finance_settings', ['finance_owner_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_loan_renewals_old_loan_id'), table_name='loan_renewals')
    op.drop_index(op.f('ix_loan_renewals_new_loan_id'), table_name='loan_renewals')
    op.drop_index(op.f('ix_loan_renewals_id'), table_name='loan_renewals')
    op.drop_index(op.f('ix_loan_renewals_finance_owner_id'), table_name='loan_renewals')
    op.drop_table('loan_renewals')
    # ### end Alembic commands ###
