"""add settlement fields to loans

Revision ID: 9733edf82e86
Revises: 5aea05f41e4a
Create Date: 2026-07-23 09:34:51.234930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9733edf82e86'
down_revision: Union[str, Sequence[str], None] = '5aea05f41e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('settlement_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('loans', sa.Column('waived_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('loans', sa.Column('settlement_date', sa.Date(), nullable=True))
    op.add_column('loans', sa.Column('settlement_reason', sa.String(length=255), nullable=True))
    op.add_column('loans', sa.Column('closure_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'closure_type')
    op.drop_column('loans', 'settlement_reason')
    op.drop_column('loans', 'settlement_date')
    op.drop_column('loans', 'waived_amount')
    op.drop_column('loans', 'settlement_amount')
    # ### end Alembic commands ###
